# Generated by Django 4.2.4 on 2023-09-03 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('comments', models.CharField(blank=True, max_length=200, null=True)),
                ('imported_from', models.URLField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('season', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('halftime', models.CharField(max_length=20)),
                ('result', models.CharField(max_length=20)),
                ('attendance', models.IntegerField(blank=True, null=True)),
                ('walkover', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('comments', models.CharField(blank=True, max_length=200, null=True)),
                ('imported_from', models.URLField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('logo', models.URLField()),
                ('city', models.CharField(max_length=200)),
                ('ekstraklasa', models.BooleanField(default=False)),
                ('founded', models.IntegerField()),
                ('stadium', models.CharField(max_length=200)),
                ('capacity', models.IntegerField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('comments', models.CharField(blank=True, max_length=200, null=True)),
                ('imported_from', models.URLField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('nationality', models.CharField(max_length=200)),
                ('photo', models.URLField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('injured', models.BooleanField(default=False)),
                ('position', models.CharField(max_length=200)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='squad', to='app.team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('comments', models.CharField(blank=True, max_length=200, null=True)),
                ('imported_from', models.URLField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('minute', models.IntegerField(blank=True, null=True)),
                ('penalty', models.BooleanField(default=False)),
                ('own_goal', models.BooleanField(default=False)),
                ('assistant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_assists', to='app.player')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_goals', to='app.game')),
                ('own_goal_scorer', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_player_own_goals', to='app.player')),
                ('scorer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_player_goals', to='app.player')),
                ('team_against', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_goals_lost', to='app.team')),
                ('team_scored', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_goals', to='app.team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='game',
            name='team_away',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_away', to='app.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='team_home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_home', to='app.team'),
        ),
    ]
