# Generated by Django 4.2.4 on 2023-09-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_game_imported_at_alter_game_imported_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
