# Generated by Django 4.2.4 on 2024-01-06 14:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_game_referee_game_round_goal_minute_extra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='overview',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='team',
            name='website',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='imported_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='imported_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='own_goal_scorer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_own_goals', to='app.player'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='scorer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_goals', to='app.player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='imported_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='imported_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
