# Generated by Django 4.2.4 on 2024-01-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_team_overview_team_website_alter_game_imported_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='stadium_photo',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
